./" man page for ShenzhenSolitaire
.TH ShenzhenSolitaire 6 "2021-05-31" "V1.0" "ShenzhenSolitaire man page"

.SH NAME
ShenzhenSolitaire
.SH SYNOPSIS
\[char46]/ShenzhenSolitaire [OPTION]
.SH DESCRIPTION
Linux terminal version of Shenzhen Solitaire based on the PC game made by Zachtronics.
.SH OPTIONS
.IP none
Runs the game.
.IP -h
Prints the controls for the game in the terminal and exits script.
.IP -v
Prints the version and author in terminal and exits script.
.IP -r
Opens default browser using xdg-open or gnome-open and goes to "https://shenzhen-io.fandom.com/wiki/Shenzhen_Solitaire".
.br
The page contains rules for Shenzhen Solitaire.
.SH AUTHOR
Krzysztof Kulpiński
.SH LICENCE
Licensed under GPL (see /usr/share/common-licenses/GPL for more details or contact # the Free Software Foundation for a copy)"
